.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-network-prune - Remove all unused networks


.SH SYNOPSIS
\fBdocker network prune [OPTIONS]\fP


.SH DESCRIPTION
Remove all unused networks


.SH OPTIONS
\fB--filter\fP=
	Provide filter values (e.g. "until=")

.PP
\fB-f\fP, \fB--force\fP[=false]
	Do not prompt for confirmation

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for prune


.SH SEE ALSO
\fBdocker-network(1)\fP
