.nh
.TH "DOCKER" "1" "Jan 2024" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-container-restart - Restart one or more containers


.SH SYNOPSIS
.PP
\fBdocker container restart [OPTIONS] CONTAINER [CONTAINER...]\fP


.SH DESCRIPTION
.PP
Restart each container listed.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for restart

.PP
\fB-s\fP, \fB--signal\fP=""
	Signal to send to the container

.PP
\fB-t\fP, \fB--time\fP=0
	Seconds to wait before killing the container


.SH SEE ALSO
.PP
\fBdocker-container(1)\fP
