.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-container-rename - Rename a container


.SH SYNOPSIS
\fBdocker container rename CONTAINER NEW_NAME\fP


.SH DESCRIPTION
Rename a container.  Container may be running, paused or stopped.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for rename


.SH SEE ALSO
\fBdocker-container(1)\fP
