.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-plugin-ls - List plugins


.SH SYNOPSIS
\fBdocker plugin ls [OPTIONS]\fP


.SH DESCRIPTION
Lists all the plugins that are currently installed. You can install plugins
using the \fBdocker plugin install\fR command.
You can also filter using the \fB-f\fR or \fB--filter\fR flag.

.SH Filters
Filter output based on these conditions:
   - enabled=(true|false) - plugins that are enabled or not
   - capability= - filters plugins based on capabilities (currently \fBvolumedriver\fR, \fBnetworkdriver\fR, \fBipamdriver\fR, or \fBauthz\fR)

.SH Format
Format the output using the given Go template.
   Valid placeholders:
      .ID - Plugin ID.
      .Name - Plugin Name.
      .Description - Plugin description.
      .Enabled - Whether plugin is enabled or not.


.SH EXAMPLES
.SH Display all plugins
.EX
$ docker plugin ls
ID                  NAME                                    DESCRIPTION                         ENABLED
869080b57404        tiborvass/sample-volume-plugin:latest   A sample volume plugin for Docker   true
141bf6c02ddd        vieux/sshfs:latest                      sshFS plugin for Docker             false
.EE

.SH Display plugins with their ID and names
.EX
$ docker plugin ls --format "{{.ID}}: {{.Name}}"
869080b57404: tiborvass/sample-volume-plugin:latest
.EE

.SH Display plugins in JSON format
.EX
$ docker plugin ls --format json
{"Description":"A sample volume plugin for Docker","Enabled":true,"ID":"2788a2da7e12","Name":"tiborvass/sample-volume-plugin:latest","PluginReference":"docker.io/tiborvass/sample-volume-plugin:latest"}
.EE

.SH Display enabled plugins
.EX
$ docker plugin ls --filter enabled=true
ID                  NAME                                    DESCRIPTION                         ENABLED
869080b57404        tiborvass/sample-volume-plugin:latest   A sample volume plugin for Docker   true
.EE

.SH Display plugins with \fBvolumedriver\fR capability
.EX
$ docker plugin ls --filter capability=volumedriver --format "table {{.ID}}\\t{{.Name}}"
ID                  Name
869080b57404        tiborvass/sample-volume-plugin:latest
.EE


.SH OPTIONS
\fB-f\fP, \fB--filter\fP=
	Provide filter values (e.g. "enabled=true")

.PP
\fB--format\fP=""
	Format output using a custom template:
\&'table':            Print output in table format with column headers (default)
\&'table TEMPLATE':   Print output in table format using the given Go template
\&'json':             Print in JSON format
\&'TEMPLATE':         Print output using the given Go template.
Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for ls

.PP
\fB--no-trunc\fP[=false]
	Don't truncate output

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Only display plugin IDs


.SH SEE ALSO
\fBdocker-plugin(1)\fP
