.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-plugin-push - Push a plugin to a registry


.SH SYNOPSIS
\fBdocker plugin push [OPTIONS] PLUGIN[:TAG]\fP


.SH DESCRIPTION
Push a plugin to a registry


.SH OPTIONS
\fB--disable-content-trust\fP[=true]
	Skip image signing

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for push


.SH SEE ALSO
\fBdocker-plugin(1)\fP
