.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-system - Manage Docker


.SH SYNOPSIS
\fBdocker system\fP


.SH DESCRIPTION
Manage Docker


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for system


.SH SEE ALSO
\fBdocker(1)\fP, \fBdocker-system-df(1)\fP, \fBdocker-system-events(1)\fP, \fBdocker-system-info(1)\fP, \fBdocker-system-prune(1)\fP
