.nh
.TH "DOCKER" "1" "Aug 2023" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-image-inspect - Display detailed information on one or more images


.SH SYNOPSIS
.PP
\fBdocker image inspect [OPTIONS] IMAGE [IMAGE...]\fP


.SH DESCRIPTION
.PP
Display detailed information on one or more images


.SH OPTIONS
.PP
\fB-f\fP, \fB--format\fP=""
	Format output using a custom template:
'json':             Print in JSON format
'TEMPLATE':         Print output using the given Go template.
Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for inspect


.SH SEE ALSO
.PP
\fBdocker-image(1)\fP
