.nh
.TH "DOCKER" "1" "Jun 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-node-inspect - Display detailed information on one or more nodes


.SH SYNOPSIS
\fBdocker node inspect [OPTIONS] self|NODE [NODE...]\fP


.SH DESCRIPTION
Display detailed information on one or more nodes


.SH OPTIONS
\fB-f\fP, \fB--format\fP=""
	Format output using a custom template:
\&'json':             Print in JSON format
\&'TEMPLATE':         Print output using the given Go template.
Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates

.PP
\fB--pretty\fP[=false]
	Print the information in a human friendly format


.SH SEE ALSO
\fBdocker-node(1)\fP
