.nh
.TH "DOCKER" "1" "Jan 2024" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-rename - Rename a container


.SH SYNOPSIS
.PP
\fBdocker rename CONTAINER NEW_NAME\fP


.SH DESCRIPTION
.PP
Alias for \fBdocker container rename\fR\&.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for rename


.SH SEE ALSO
.PP
\fBdocker(1)\fP
