.nh
.TH "DOCKER" "1" "Jun 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-export - Export a container's filesystem as a tar archive


.SH SYNOPSIS
\fBdocker export [OPTIONS] CONTAINER\fP


.SH DESCRIPTION
Alias for \fBdocker container export\fR\&.


.SH OPTIONS
\fB-o\fP, \fB--output\fP=""
	Write to a file, instead of STDOUT


.SH SEE ALSO
\fBdocker(1)\fP
