.nh
.TH "DOCKER" "1" "Jun 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-checkpoint-rm - Remove a checkpoint


.SH SYNOPSIS
\fBdocker checkpoint rm [OPTIONS] CONTAINER CHECKPOINT\fP


.SH DESCRIPTION
Remove a checkpoint


.SH OPTIONS
\fB--checkpoint-dir\fP=""
	Use a custom checkpoint storage directory


.SH SEE ALSO
\fBdocker-checkpoint(1)\fP
