.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-trust-signer-add - Add a signer


.SH SYNOPSIS
**docker trust signer add OPTIONS NAME REPOSITORY [REPOSITORY...] **


.SH DESCRIPTION
Add a signer


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for add

.PP
\fB--key\fP=
	Path to the signer's public key file


.SH SEE ALSO
\fBdocker-trust-signer(1)\fP
