.nh
.TH "DOCKER" "1" "Dec 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-system-df - Show docker disk usage


.SH SYNOPSIS
\fBdocker system df [OPTIONS]\fP


.SH DESCRIPTION
Show docker disk usage


.SH OPTIONS
\fB--format\fP=""
	Format output using a custom template:
\&'table':            Print output in table format with column headers (default)
\&'table TEMPLATE':   Print output in table format using the given Go template
\&'json':             Print in JSON format
\&'TEMPLATE':         Print output using the given Go template.
Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Show detailed information on space usage


.SH SEE ALSO
\fBdocker-system(1)\fP
