.nh
.TH "DOCKER" "1" "Jan 2024" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-manifest-rm - Delete one or more manifest lists from local storage


.SH SYNOPSIS
.PP
\fBdocker manifest rm MANIFEST_LIST [MANIFEST_LIST...]\fP


.SH DESCRIPTION
.PP
Delete one or more manifest lists from local storage


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for rm


.SH SEE ALSO
.PP
\fBdocker-manifest(1)\fP
