.nh
.TH "DOCKER" "1" "Aug 2023" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-builder - Manage builds


.SH SYNOPSIS
.PP
\fBdocker builder\fP


.SH DESCRIPTION
.PP
Manage builds


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for builder


.SH SEE ALSO
.PP
\fBdocker(1)\fP, \fBdocker-builder-build(1)\fP, \fBdocker-builder-prune(1)\fP
