.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-history - Show the history of an image


.SH SYNOPSIS
\fBdocker history [OPTIONS] IMAGE\fP


.SH DESCRIPTION
Alias for \fBdocker image history\fR\&.


.SH OPTIONS
\fB--format\fP=""
	Format output using a custom template:
\&'table':            Print output in table format with column headers (default)
\&'table TEMPLATE':   Print output in table format using the given Go template
\&'json':             Print in JSON format
\&'TEMPLATE':         Print output using the given Go template.
Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates

.PP
\fB-H\fP, \fB--human\fP[=true]
	Print sizes and dates in human readable format

.PP
\fB--no-trunc\fP[=false]
	Don't truncate output

.PP
\fB--platform\fP=""
	Show history for the given platform. Formatted as "os[/arch[/variant]]" (e.g., "linux/amd64")

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Only show image IDs


.SH SEE ALSO
\fBdocker(1)\fP
