.nh
.TH "DOCKER" "1" "Jun 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-container-inspect - Display detailed information on one or more containers


.SH SYNOPSIS
\fBdocker container inspect [OPTIONS] CONTAINER [CONTAINER...]\fP


.SH DESCRIPTION
Display detailed information on one or more containers


.SH OPTIONS
\fB-f\fP, \fB--format\fP=""
	Format output using a custom template:
\&'json':             Print in JSON format
\&'TEMPLATE':         Print output using the given Go template.
Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates

.PP
\fB-s\fP, \fB--size\fP[=false]
	Display total file sizes


.SH SEE ALSO
\fBdocker-container(1)\fP
