.nh
.TH "DOCKER" "1" "Dec 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-volume-update - Update a volume (cluster volumes only)


.SH SYNOPSIS
\fBdocker volume update [OPTIONS] [VOLUME]\fP


.SH DESCRIPTION
Update a volume (cluster volumes only)


.SH OPTIONS
\fB--availability\fP="active"
	Cluster Volume availability ("active", "pause", "drain")


.SH SEE ALSO
\fBdocker-volume(1)\fP
