.nh
.TH "DOCKER" "1" "Dec 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-rm - Remove one or more containers


.SH SYNOPSIS
\fBdocker rm [OPTIONS] CONTAINER [CONTAINER...]\fP


.SH DESCRIPTION
Alias for \fBdocker container rm\fR\&.


.SH OPTIONS
\fB-f\fP, \fB--force\fP[=false]
	Force the removal of a running container (uses SIGKILL)

.PP
\fB-l\fP, \fB--link\fP[=false]
	Remove the specified link

.PP
\fB-v\fP, \fB--volumes\fP[=false]
	Remove anonymous volumes associated with the container


.SH SEE ALSO
\fBdocker(1)\fP
