.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-plugin-enable - Enable a plugin


.SH SYNOPSIS
\fBdocker plugin enable [OPTIONS] PLUGIN\fP


.SH DESCRIPTION
Enable a plugin


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for enable

.PP
\fB--timeout\fP=30
	HTTP client timeout (in seconds)


.SH SEE ALSO
\fBdocker-plugin(1)\fP
