.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-diff - Inspect changes to files or directories on a container's filesystem


.SH SYNOPSIS
\fBdocker diff CONTAINER\fP


.SH DESCRIPTION
Alias for \fBdocker container diff\fR\&.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for diff


.SH SEE ALSO
\fBdocker(1)\fP
