.nh
.TH "DOCKER" "1" "Jan 2024" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-volume-prune - Remove unused local volumes


.SH SYNOPSIS
.PP
\fBdocker volume prune [OPTIONS]\fP


.SH DESCRIPTION
.PP
Remove unused local volumes


.SH OPTIONS
.PP
\fB-a\fP, \fB--all\fP[=false]
	Remove all unused volumes, not just anonymous ones

.PP
\fB--filter\fP=
	Provide filter values (e.g. "label=")

.PP
\fB-f\fP, \fB--force\fP[=false]
	Do not prompt for confirmation

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for prune


.SH SEE ALSO
.PP
\fBdocker-volume(1)\fP
