.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-container-stop - Stop one or more running containers


.SH SYNOPSIS
\fBdocker container stop [OPTIONS] CONTAINER [CONTAINER...]\fP


.SH DESCRIPTION
Stop a container (Send SIGTERM, and then SIGKILL after grace period)


.SH OPTIONS
\fB-s\fP, \fB--signal\fP=""
	Signal to send to the container

.PP
\fB-t\fP, \fB--timeout\fP=0
	Seconds to wait before killing the container


.SH SEE ALSO
\fBdocker-container(1)\fP
