.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-secret - Manage Swarm secrets


.SH SYNOPSIS
\fBdocker secret\fP


.SH DESCRIPTION
Manage Swarm secrets


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for secret


.SH SEE ALSO
\fBdocker(1)\fP, \fBdocker-secret-create(1)\fP, \fBdocker-secret-inspect(1)\fP, \fBdocker-secret-ls(1)\fP, \fBdocker-secret-rm(1)\fP
