.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-events - Get real time events from the server


.SH SYNOPSIS
\fBdocker events [OPTIONS]\fP


.SH DESCRIPTION
Alias for \fBdocker system events\fR\&.


.SH OPTIONS
\fB-f\fP, \fB--filter\fP=
	Filter output based on conditions provided

.PP
\fB--format\fP=""
	Format output using a custom template:
\&'json':             Print in JSON format
\&'TEMPLATE':         Print output using the given Go template.
Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for events

.PP
\fB--since\fP=""
	Show all events created since timestamp

.PP
\fB--until\fP=""
	Stream events until this timestamp


.SH SEE ALSO
\fBdocker(1)\fP
