.nh
.TH "DOCKER" "1" "Jun 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-trust-sign - Sign an image


.SH SYNOPSIS
\fBdocker trust sign IMAGE:TAG\fP


.SH DESCRIPTION
Sign an image


.SH OPTIONS
\fB--local\fP[=false]
	Sign a locally tagged image


.SH SEE ALSO
\fBdocker-trust(1)\fP
