.nh
.TH "DOCKER" "1" "Jan 2024" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-secret - Manage Swarm secrets


.SH SYNOPSIS
.PP
\fBdocker secret\fP


.SH DESCRIPTION
.PP
Manage Swarm secrets


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for secret


.SH SEE ALSO
.PP
\fBdocker(1)\fP, \fBdocker-secret-create(1)\fP, \fBdocker-secret-inspect(1)\fP, \fBdocker-secret-ls(1)\fP, \fBdocker-secret-rm(1)\fP
