.nh
.TH "DOCKER" "1" "Jun 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-volume-ls - List volumes


.SH SYNOPSIS
\fBdocker volume ls [OPTIONS]\fP


.SH DESCRIPTION
Lists all the volumes Docker manages. You can filter using the \fB-f\fR or
\fB--filter\fR flag. The filtering format is a \fBkey=value\fR pair. To specify
more than one filter,  pass multiple flags (for example,
\fB--filter "foo=bar" --filter "bif=baz"\fR)

.PP
The currently supported filters are:
.IP \(bu 2
\fBdangling\fR (boolean - \fBtrue\fR or \fBfalse\fR, \fB1\fR or \fB0\fR)
.IP \(bu 2
\fBdriver\fR (a volume driver's name)
.IP \(bu 2
\fBlabel\fR (\fBlabel=<key>\fR or \fBlabel=<key>=<value>\fR)
.IP \(bu 2
\fBname\fR (a volume's name)


.SH OPTIONS
\fB--cluster\fP[=false]
	Display only cluster volumes, and use cluster volume list formatting

.PP
\fB-f\fP, \fB--filter\fP=
	Provide filter values (e.g. "dangling=true")

.PP
\fB--format\fP=""
	Format output using a custom template:
\&'table':            Print output in table format with column headers (default)
\&'table TEMPLATE':   Print output in table format using the given Go template
\&'json':             Print in JSON format
\&'TEMPLATE':         Print output using the given Go template.
Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Only display volume names


.SH SEE ALSO
\fBdocker-volume(1)\fP
