.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-swarm-join - Join a swarm as a node and/or manager


.SH SYNOPSIS
\fBdocker swarm join [OPTIONS] HOST:PORT\fP


.SH DESCRIPTION
Join a swarm as a node and/or manager


.SH OPTIONS
\fB--advertise-addr\fP=""
	Advertised address (format: "[:port]")

.PP
\fB--availability\fP="active"
	Availability of the node ("active", "pause", "drain")

.PP
\fB--data-path-addr\fP=""
	Address or interface to use for data path traffic (format: "")

.PP
\fB--listen-addr\fP=0.0.0.0:2377
	Listen address (format: "[:port]")

.PP
\fB--token\fP=""
	Token for entry into the swarm


.SH SEE ALSO
\fBdocker-swarm(1)\fP
