.nh
.TH "DOCKER" "1" "Jan 2024" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-import - Import the contents from a tarball to create a filesystem image


.SH SYNOPSIS
.PP
\fBdocker import [OPTIONS] file|URL|- [REPOSITORY[:TAG]]\fP


.SH DESCRIPTION
.PP
Alias for \fBdocker image import\fR\&.


.SH OPTIONS
.PP
\fB-c\fP, \fB--change\fP=
	Apply Dockerfile instruction to the created image

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for import

.PP
\fB-m\fP, \fB--message\fP=""
	Set commit message for imported image

.PP
\fB--platform\fP=""
	Set platform if server is multi-platform capable


.SH SEE ALSO
.PP
\fBdocker(1)\fP
