.nh
.TH "DOCKER" "1" "Jan 2024" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-pull - Download an image from a registry


.SH SYNOPSIS
.PP
\fBdocker pull [OPTIONS] NAME[:TAG|@DIGEST]\fP


.SH DESCRIPTION
.PP
Alias for \fBdocker image pull\fR\&.


.SH OPTIONS
.PP
\fB-a\fP, \fB--all-tags\fP[=false]
	Download all tagged images in the repository

.PP
\fB--disable-content-trust\fP[=true]
	Skip image verification

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for pull

.PP
\fB--platform\fP=""
	Set platform if server is multi-platform capable

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose output


.SH SEE ALSO
.PP
\fBdocker(1)\fP
