.nh
.TH "DOCKER" "1" "Jun 2024" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-stack-rm - Remove one or more stacks


.SH SYNOPSIS
.PP
\fBdocker stack rm [OPTIONS] STACK [STACK...]\fP


.SH DESCRIPTION
.PP
Remove one or more stacks


.SH OPTIONS
.PP
\fB-d\fP, \fB--detach\fP[=true]
	Do not wait for stack removal

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for rm


.SH SEE ALSO
.PP
\fBdocker-stack(1)\fP
