.nh
.TH "DOCKER" "1" "Dec 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-images - List images


.SH SYNOPSIS
\fBdocker images [OPTIONS] [REPOSITORY[:TAG]]\fP


.SH DESCRIPTION
Alias for \fBdocker image ls\fR\&.


.SH OPTIONS
\fB-a\fP, \fB--all\fP[=false]
	Show all images (default hides intermediate images)

.PP
\fB--digests\fP[=false]
	Show digests

.PP
\fB-f\fP, \fB--filter\fP=
	Filter output based on conditions provided

.PP
\fB--format\fP=""
	Format output using a custom template:
\&'table':            Print output in table format with column headers (default)
\&'table TEMPLATE':   Print output in table format using the given Go template
\&'json':             Print in JSON format
\&'TEMPLATE':         Print output using the given Go template.
Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates

.PP
\fB--no-trunc\fP[=false]
	Don't truncate output

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Only show image IDs

.PP
\fB--tree\fP[=false]
	List multi-platform images as a tree (EXPERIMENTAL)


.SH SEE ALSO
\fBdocker(1)\fP
