.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-container-restart - Restart one or more containers


.SH SYNOPSIS
\fBdocker container restart [OPTIONS] CONTAINER [CONTAINER...]\fP


.SH DESCRIPTION
Restart each container listed.


.SH OPTIONS
\fB-s\fP, \fB--signal\fP=""
	Signal to send to the container

.PP
\fB-t\fP, \fB--timeout\fP=0
	Seconds to wait before killing the container


.SH SEE ALSO
\fBdocker-container(1)\fP
