.nh
.TH "DOCKER" "1" "Jun 2024" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-stats - Display a live stream of container(s) resource usage statistics


.SH SYNOPSIS
.PP
\fBdocker stats [OPTIONS] [CONTAINER...]\fP


.SH DESCRIPTION
.PP
Alias for \fBdocker container stats\fR\&.


.SH OPTIONS
.PP
\fB-a\fP, \fB--all\fP[=false]
	Show all containers (default shows just running)

.PP
\fB--format\fP=""
	Format output using a custom template:
'table':            Print output in table format with column headers (default)
'table TEMPLATE':   Print output in table format using the given Go template
'json':             Print in JSON format
'TEMPLATE':         Print output using the given Go template.
Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for stats

.PP
\fB--no-stream\fP[=false]
	Disable streaming stats and only pull the first result

.PP
\fB--no-trunc\fP[=false]
	Do not truncate output


.SH SEE ALSO
.PP
\fBdocker(1)\fP
