.nh
.TH "DOCKER" "1" "Dec 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-manifest-inspect - Display an image manifest, or manifest list


.SH SYNOPSIS
\fBdocker manifest inspect [OPTIONS] [MANIFEST_LIST] MANIFEST\fP


.SH DESCRIPTION
Display an image manifest, or manifest list


.SH OPTIONS
\fB--insecure\fP[=false]
	Allow communication with an insecure registry

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Output additional info including layers and platform


.SH SEE ALSO
\fBdocker-manifest(1)\fP
