.nh
.TH "DOCKER" "1" "Jun 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-config - Manage Swarm configs


.SH SYNOPSIS
\fBdocker config\fP


.SH DESCRIPTION
Manage Swarm configs


.SH SEE ALSO
\fBdocker(1)\fP, \fBdocker-config-create(1)\fP, \fBdocker-config-inspect(1)\fP, \fBdocker-config-ls(1)\fP, \fBdocker-config-rm(1)\fP
