.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-trust - Manage trust on Docker images


.SH SYNOPSIS
\fBdocker trust\fP


.SH DESCRIPTION
Manage trust on Docker images


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for trust


.SH SEE ALSO
\fBdocker(1)\fP, \fBdocker-trust-inspect(1)\fP, \fBdocker-trust-key(1)\fP, \fBdocker-trust-revoke(1)\fP, \fBdocker-trust-sign(1)\fP, \fBdocker-trust-signer(1)\fP
