.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-trust-inspect - Return low-level information about keys and signatures


.SH SYNOPSIS
\fBdocker trust inspect IMAGE[:TAG] [IMAGE[:TAG]...]\fP


.SH DESCRIPTION
Return low-level information about keys and signatures


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for inspect

.PP
\fB--pretty\fP[=false]
	Print the information in a human friendly format


.SH SEE ALSO
\fBdocker-trust(1)\fP
