.nh
.TH "DOCKER" "1" "Dec 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-node-rm - Remove one or more nodes from the swarm


.SH SYNOPSIS
\fBdocker node rm [OPTIONS] NODE [NODE...]\fP


.SH DESCRIPTION
Remove one or more nodes from the swarm


.SH OPTIONS
\fB-f\fP, \fB--force\fP[=false]
	Force remove a node from the swarm


.SH SEE ALSO
\fBdocker-node(1)\fP
