.nh
.TH "DOCKER" "1" "Jun 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-container-prune - Remove all stopped containers


.SH SYNOPSIS
\fBdocker container prune [OPTIONS]\fP


.SH DESCRIPTION
Remove all stopped containers


.SH OPTIONS
\fB--filter\fP=
	Provide filter values (e.g. "until=")

.PP
\fB-f\fP, \fB--force\fP[=false]
	Do not prompt for confirmation


.SH SEE ALSO
\fBdocker-container(1)\fP
