.nh
.TH "DOCKER" "1" "Dec 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-save - Save one or more images to a tar archive (streamed to STDOUT by default)


.SH SYNOPSIS
\fBdocker save [OPTIONS] IMAGE [IMAGE...]\fP


.SH DESCRIPTION
Alias for \fBdocker image save\fR\&.


.SH OPTIONS
\fB-o\fP, \fB--output\fP=""
	Write to a file, instead of STDOUT

.PP
\fB--platform\fP=[]
	Save only the given platform(s). Formatted as a comma-separated list of "os[/arch[/variant]]" (e.g., "linux/amd64,linux/arm64/v8")


.SH SEE ALSO
\fBdocker(1)\fP
