.nh
.TH "DOCKER" "1" "Jun 2024" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-info - Display system-wide information


.SH SYNOPSIS
.PP
\fBdocker info [OPTIONS]\fP


.SH DESCRIPTION
.PP
Alias for \fBdocker system info\fR\&.


.SH OPTIONS
.PP
\fB-f\fP, \fB--format\fP=""
	Format output using a custom template:
'json':             Print in JSON format
'TEMPLATE':         Print output using the given Go template.
Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for info


.SH SEE ALSO
.PP
\fBdocker(1)\fP
