.nh
.TH "DOCKER" "1" "Jun 2024" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-context-use - Set the current docker context


.SH SYNOPSIS
.PP
\fBdocker context use CONTEXT\fP


.SH DESCRIPTION
.PP
Set the current docker context


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for use


.SH SEE ALSO
.PP
\fBdocker-context(1)\fP
