.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-plugin-install - Install a plugin


.SH SYNOPSIS
\fBdocker plugin install [OPTIONS] PLUGIN [KEY=VALUE...]\fP


.SH DESCRIPTION
Install a plugin


.SH OPTIONS
\fB--alias\fP=""
	Local name for plugin

.PP
\fB--disable\fP[=false]
	Do not enable the plugin on install

.PP
\fB--disable-content-trust\fP[=true]
	Skip image verification

.PP
\fB--grant-all-permissions\fP[=false]
	Grant all permissions necessary to run the plugin

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for install


.SH SEE ALSO
\fBdocker-plugin(1)\fP
