.nh
.TH "DOCKER" "1" "Dec 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-stack-services - List the services in the stack


.SH SYNOPSIS
\fBdocker stack services [OPTIONS] STACK\fP


.SH DESCRIPTION
List the services in the stack


.SH OPTIONS
\fB-f\fP, \fB--filter\fP=
	Filter output based on conditions provided

.PP
\fB--format\fP=""
	Format output using a custom template:
\&'table':            Print output in table format with column headers (default)
\&'table TEMPLATE':   Print output in table format using the given Go template
\&'json':             Print in JSON format
\&'TEMPLATE':         Print output using the given Go template.
Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Only display IDs


.SH SEE ALSO
\fBdocker-stack(1)\fP
