.nh
.TH "DOCKER" "1" "Dec 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-plugin-upgrade - Upgrade an existing plugin


.SH SYNOPSIS
\fBdocker plugin upgrade [OPTIONS] PLUGIN [REMOTE]\fP


.SH DESCRIPTION
Upgrade an existing plugin


.SH OPTIONS
\fB--grant-all-permissions\fP[=false]
	Grant all permissions necessary to run the plugin

.PP
\fB--skip-remote-check\fP[=false]
	Do not check if specified remote plugin matches existing plugin image


.SH SEE ALSO
\fBdocker-plugin(1)\fP
