.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-save - Save one or more images to a tar archive (streamed to STDOUT by default)


.SH SYNOPSIS
\fBdocker save [OPTIONS] IMAGE [IMAGE...]\fP


.SH DESCRIPTION
Alias for \fBdocker image save\fR\&.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for save

.PP
\fB-o\fP, \fB--output\fP=""
	Write to a file, instead of STDOUT


.SH SEE ALSO
\fBdocker(1)\fP
