.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-config-create - Create a config from a file or STDIN


.SH SYNOPSIS
\fBdocker config create [OPTIONS] CONFIG file|-\fP


.SH DESCRIPTION
Create a config from a file or STDIN


.SH OPTIONS
\fB-l\fP, \fB--label\fP=
	Config labels

.PP
\fB--template-driver\fP=""
	Template driver


.SH SEE ALSO
\fBdocker-config(1)\fP
