.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-trust-signer - Manage entities who can sign Docker images


.SH SYNOPSIS
\fBdocker trust signer\fP


.SH DESCRIPTION
Manage entities who can sign Docker images


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for signer


.SH SEE ALSO
\fBdocker-trust(1)\fP, \fBdocker-trust-signer-add(1)\fP, \fBdocker-trust-signer-remove(1)\fP
