.nh
.TH "DOCKER" "1" "Jun 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-plugin-disable - Disable a plugin


.SH SYNOPSIS
\fBdocker plugin disable [OPTIONS] PLUGIN\fP


.SH DESCRIPTION
Disable a plugin


.SH OPTIONS
\fB-f\fP, \fB--force\fP[=false]
	Force the disable of an active plugin


.SH SEE ALSO
\fBdocker-plugin(1)\fP
