.nh
.TH "DOCKER" "1" "Aug 2023" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-stack-ls - List stacks


.SH SYNOPSIS
.PP
\fBdocker stack ls [OPTIONS]\fP


.SH DESCRIPTION
.PP
List stacks


.SH OPTIONS
.PP
\fB--format\fP=""
	Format output using a custom template:
'table':            Print output in table format with column headers (default)
'table TEMPLATE':   Print output in table format using the given Go template
'json':             Print in JSON format
'TEMPLATE':         Print output using the given Go template.
Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for ls


.SH SEE ALSO
.PP
\fBdocker-stack(1)\fP
