.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-stack-rm - Remove one or more stacks


.SH SYNOPSIS
\fBdocker stack rm [OPTIONS] STACK [STACK...]\fP


.SH DESCRIPTION
Remove one or more stacks


.SH OPTIONS
\fB-d\fP, \fB--detach\fP[=true]
	Do not wait for stack removal


.SH SEE ALSO
\fBdocker-stack(1)\fP
