.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-node-promote - Promote one or more nodes to manager in the swarm


.SH SYNOPSIS
\fBdocker node promote NODE [NODE...]\fP


.SH DESCRIPTION
Promote one or more nodes to manager in the swarm


.SH SEE ALSO
\fBdocker-node(1)\fP
