.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-swarm-leave - Leave the swarm


.SH SYNOPSIS
\fBdocker swarm leave [OPTIONS]\fP


.SH DESCRIPTION
Leave the swarm


.SH OPTIONS
\fB-f\fP, \fB--force\fP[=false]
	Force this node to leave the swarm, ignoring warnings


.SH SEE ALSO
\fBdocker-swarm(1)\fP
