.nh
.TH "DOCKER" "1" "Jun 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-image-rm - Remove one or more images


.SH SYNOPSIS
\fBdocker image rm [OPTIONS] IMAGE [IMAGE...]\fP


.SH DESCRIPTION
Removes (and un-tags) one or more images from the host node. If an image has
multiple tags, using this command with the tag as a parameter only removes the
tag. If the tag is the only one for the image, both the image and the tag are
removed.

.PP
This does not remove images from a registry. You cannot remove an image of a
running container unless you use the \fB-f\fP option. To see all images on a host
use the \fBdocker image ls\fP command.


.SH EXAMPLES
.SH Removing an image
Here is an example of removing an image:

.EX
docker image rm fedora/httpd
.EE


.SH OPTIONS
\fB-f\fP, \fB--force\fP[=false]
	Force removal of the image

.PP
\fB--no-prune\fP[=false]
	Do not delete untagged parents

.PP
\fB--platform\fP=[]
	Remove only the given platform variant. Formatted as "os[/arch[/variant]]" (e.g., "linux/amd64")


.SH SEE ALSO
\fBdocker-image(1)\fP
