.nh
.TH "DOCKER" "1" "Dec 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-manifest-rm - Delete one or more manifest lists from local storage


.SH SYNOPSIS
\fBdocker manifest rm MANIFEST_LIST [MANIFEST_LIST...]\fP


.SH DESCRIPTION
Delete one or more manifest lists from local storage


.SH SEE ALSO
\fBdocker-manifest(1)\fP
