.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-manifest-create - Create a local manifest list for annotating and pushing to a registry


.SH SYNOPSIS
\fBdocker manifest create MANIFEST_LIST MANIFEST [MANIFEST...]\fP


.SH DESCRIPTION
Create a local manifest list for annotating and pushing to a registry


.SH OPTIONS
\fB-a\fP, \fB--amend\fP[=false]
	Amend an existing manifest list

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for create

.PP
\fB--insecure\fP[=false]
	Allow communication with an insecure registry


.SH SEE ALSO
\fBdocker-manifest(1)\fP
