.nh
.TH "DOCKER" "1" "Dec 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-service-scale - Scale one or multiple replicated services


.SH SYNOPSIS
\fBdocker service scale SERVICE=REPLICAS [SERVICE=REPLICAS...]\fP


.SH DESCRIPTION
Scale one or multiple replicated services


.SH OPTIONS
\fB-d\fP, \fB--detach\fP[=false]
	Exit immediately instead of waiting for the service to converge


.SH SEE ALSO
\fBdocker-service(1)\fP
