.nh
.TH "DOCKER" "1" "Jun 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-network-prune - Remove all unused networks


.SH SYNOPSIS
\fBdocker network prune [OPTIONS]\fP


.SH DESCRIPTION
Remove all unused networks


.SH OPTIONS
\fB--filter\fP=
	Provide filter values (e.g. "until=")

.PP
\fB-f\fP, \fB--force\fP[=false]
	Do not prompt for confirmation


.SH SEE ALSO
\fBdocker-network(1)\fP
