.nh
.TH "DOCKER" "1" "Dec 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-plugin - Manage plugins


.SH SYNOPSIS
\fBdocker plugin\fP


.SH DESCRIPTION
Manage plugins


.SH SEE ALSO
\fBdocker(1)\fP, \fBdocker-plugin-create(1)\fP, \fBdocker-plugin-disable(1)\fP, \fBdocker-plugin-enable(1)\fP, \fBdocker-plugin-inspect(1)\fP, \fBdocker-plugin-install(1)\fP, \fBdocker-plugin-ls(1)\fP, \fBdocker-plugin-push(1)\fP, \fBdocker-plugin-rm(1)\fP, \fBdocker-plugin-set(1)\fP, \fBdocker-plugin-upgrade(1)\fP
