.nh
.TH "DOCKER" "1" "Aug 2023" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-context-show - Print the name of the current context


.SH SYNOPSIS
.PP
\fBdocker context show\fP


.SH DESCRIPTION
.PP
Print the name of the current context


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for show


.SH SEE ALSO
.PP
\fBdocker-context(1)\fP
