.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-trust-signer-remove - Remove a signer


.SH SYNOPSIS
\fBdocker trust signer remove [OPTIONS] NAME REPOSITORY [REPOSITORY...]\fP


.SH DESCRIPTION
Remove a signer


.SH OPTIONS
\fB-f\fP, \fB--force\fP[=false]
	Do not prompt for confirmation before removing the most recent signer

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for remove


.SH SEE ALSO
\fBdocker-trust-signer(1)\fP
