.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-network-rm - Remove one or more networks


.SH SYNOPSIS
\fBdocker network rm NETWORK [NETWORK...]\fP


.SH DESCRIPTION
Removes one or more networks by name or identifier. To remove a network,
you must first disconnect any containers connected to it.
To remove the network named 'my-network':

.EX
$ docker network rm my-network
.EE

.PP
To delete multiple networks in a single \fBdocker network rm\fR command, provide
multiple network names or ids. The following example deletes a network with id
\fB3695c422697f\fR and a network named \fBmy-network\fR:

.EX
$ docker network rm 3695c422697f my-network
.EE

.PP
When you specify multiple networks, the command attempts to delete each in turn.
If the deletion of one network fails, the command continues to the next on the
list and tries to delete that. The command reports success or failure for each
deletion.


.SH OPTIONS
\fB-f\fP, \fB--force\fP[=false]
	Do not error if the network does not exist


.SH SEE ALSO
\fBdocker-network(1)\fP
