.nh
.TH "DOCKER" "1" "Jan 2024" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-context-inspect - Display detailed information on one or more contexts


.SH SYNOPSIS
.PP
\fBdocker context inspect [OPTIONS] [CONTEXT] [CONTEXT...]\fP


.SH DESCRIPTION
.PP
Display detailed information on one or more contexts


.SH OPTIONS
.PP
\fB-f\fP, \fB--format\fP=""
	Format output using a custom template:
'json':             Print in JSON format
'TEMPLATE':         Print output using the given Go template.
Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for inspect


.SH SEE ALSO
.PP
\fBdocker-context(1)\fP
