.nh
.TH "DOCKER" "1" "Aug 2023" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-stack - Manage Swarm stacks


.SH SYNOPSIS
.PP
\fBdocker stack [OPTIONS]\fP


.SH DESCRIPTION
.PP
Manage Swarm stacks


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for stack


.SH SEE ALSO
.PP
\fBdocker(1)\fP, \fBdocker-stack-config(1)\fP, \fBdocker-stack-deploy(1)\fP, \fBdocker-stack-ls(1)\fP, \fBdocker-stack-ps(1)\fP, \fBdocker-stack-rm(1)\fP, \fBdocker-stack-services(1)\fP
