.nh
.TH "DOCKER" "1" "Dec 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-plugin-inspect - Display detailed information on one or more plugins


.SH SYNOPSIS
\fBdocker plugin inspect [OPTIONS] PLUGIN [PLUGIN...]\fP


.SH DESCRIPTION
Display detailed information on one or more plugins


.SH OPTIONS
\fB-f\fP, \fB--format\fP=""
	Format output using a custom template:
\&'json':             Print in JSON format
\&'TEMPLATE':         Print output using the given Go template.
Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates


.SH SEE ALSO
\fBdocker-plugin(1)\fP
