.nh
.TH "DOCKER" "1" "Jun 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-stack-config - Outputs the final config file, after doing merges and interpolations


.SH SYNOPSIS
\fBdocker stack config [OPTIONS]\fP


.SH DESCRIPTION
Outputs the final config file, after doing merges and interpolations


.SH OPTIONS
\fB-c\fP, \fB--compose-file\fP=[]
	Path to a Compose file, or "-" to read from stdin

.PP
\fB--skip-interpolation\fP[=false]
	Skip interpolation and output only merged config


.SH SEE ALSO
\fBdocker-stack(1)\fP
