.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-unpause - Unpause all processes within one or more containers


.SH SYNOPSIS
\fBdocker unpause CONTAINER [CONTAINER...]\fP


.SH DESCRIPTION
Alias for \fBdocker container unpause\fR\&.


.SH SEE ALSO
\fBdocker(1)\fP
