.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-kill - Kill one or more running containers


.SH SYNOPSIS
\fBdocker kill [OPTIONS] CONTAINER [CONTAINER...]\fP


.SH DESCRIPTION
Alias for \fBdocker container kill\fR\&.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for kill

.PP
\fB-s\fP, \fB--signal\fP=""
	Signal to send to the container


.SH SEE ALSO
\fBdocker(1)\fP
