.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-context-inspect - Display detailed information on one or more contexts


.SH SYNOPSIS
\fBdocker context inspect [OPTIONS] [CONTEXT] [CONTEXT...]\fP


.SH DESCRIPTION
Display detailed information on one or more contexts


.SH OPTIONS
\fB-f\fP, \fB--format\fP=""
	Format output using a custom template:
\&'json':             Print in JSON format
\&'TEMPLATE':         Print output using the given Go template.
Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates


.SH SEE ALSO
\fBdocker-context(1)\fP
