.nh
.TH "DOCKER" "1" "Aug 2023" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-context-export - Export a context to a tar archive FILE or a tar stream on STDOUT.


.SH SYNOPSIS
.PP
\fBdocker context export [OPTIONS] CONTEXT [FILE|-]\fP


.SH DESCRIPTION
.PP
Export a context to a tar archive FILE or a tar stream on STDOUT.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for export


.SH SEE ALSO
.PP
\fBdocker-context(1)\fP
