.nh
.TH "DOCKER" "1" "Jan 2024" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-stop - Stop one or more running containers


.SH SYNOPSIS
.PP
\fBdocker stop [OPTIONS] CONTAINER [CONTAINER...]\fP


.SH DESCRIPTION
.PP
Alias for \fBdocker container stop\fR\&.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for stop

.PP
\fB-s\fP, \fB--signal\fP=""
	Signal to send to the container

.PP
\fB-t\fP, \fB--time\fP=0
	Seconds to wait before killing the container


.SH SEE ALSO
.PP
\fBdocker(1)\fP
