.nh
.TH "DOCKER" "1" "Jun 2024" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-top - Display the running processes of a container


.SH SYNOPSIS
.PP
\fBdocker top CONTAINER [ps OPTIONS]\fP


.SH DESCRIPTION
.PP
Alias for \fBdocker container top\fR\&.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for top


.SH SEE ALSO
.PP
\fBdocker(1)\fP
