.nh
.TH "DOCKER" "1" "Dec 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-swarm - Manage Swarm


.SH SYNOPSIS
\fBdocker swarm\fP


.SH DESCRIPTION
Manage Swarm


.SH SEE ALSO
\fBdocker(1)\fP, \fBdocker-swarm-ca(1)\fP, \fBdocker-swarm-init(1)\fP, \fBdocker-swarm-join(1)\fP, \fBdocker-swarm-join-token(1)\fP, \fBdocker-swarm-leave(1)\fP, \fBdocker-swarm-unlock(1)\fP, \fBdocker-swarm-unlock-key(1)\fP, \fBdocker-swarm-update(1)\fP
