.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-system-prune - Remove unused data


.SH SYNOPSIS
\fBdocker system prune [OPTIONS]\fP


.SH DESCRIPTION
Remove unused data


.SH OPTIONS
\fB-a\fP, \fB--all\fP[=false]
	Remove all unused images not just dangling ones

.PP
\fB--filter\fP=
	Provide filter values (e.g. "label==")

.PP
\fB-f\fP, \fB--force\fP[=false]
	Do not prompt for confirmation

.PP
\fB--volumes\fP[=false]
	Prune anonymous volumes


.SH SEE ALSO
\fBdocker-system(1)\fP
