.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-service - Manage Swarm services


.SH SYNOPSIS
\fBdocker service\fP


.SH DESCRIPTION
Manage Swarm services


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for service


.SH SEE ALSO
\fBdocker(1)\fP, \fBdocker-service-create(1)\fP, \fBdocker-service-inspect(1)\fP, \fBdocker-service-logs(1)\fP, \fBdocker-service-ls(1)\fP, \fBdocker-service-ps(1)\fP, \fBdocker-service-rm(1)\fP, \fBdocker-service-rollback(1)\fP, \fBdocker-service-scale(1)\fP, \fBdocker-service-update(1)\fP
