.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-stop - Stop one or more running containers


.SH SYNOPSIS
\fBdocker stop [OPTIONS] CONTAINER [CONTAINER...]\fP


.SH DESCRIPTION
Alias for \fBdocker container stop\fR\&.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for stop

.PP
\fB-s\fP, \fB--signal\fP=""
	Signal to send to the container

.PP
\fB-t\fP, \fB--time\fP=0
	Seconds to wait before killing the container


.SH SEE ALSO
\fBdocker(1)\fP
