.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-plugin-set - Change settings for a plugin


.SH SYNOPSIS
\fBdocker plugin set PLUGIN KEY=VALUE [KEY=VALUE...]\fP


.SH DESCRIPTION
Change settings for a plugin


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for set


.SH SEE ALSO
\fBdocker-plugin(1)\fP
