.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-port - List port mappings or a specific mapping for the container


.SH SYNOPSIS
\fBdocker port CONTAINER [PRIVATE_PORT[/PROTO]]\fP


.SH DESCRIPTION
Alias for \fBdocker container port\fR\&.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for port


.SH SEE ALSO
\fBdocker(1)\fP
