.nh
.TH "DOCKER" "1" "Jun 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-context-import - Import a context from a tar or zip file


.SH SYNOPSIS
\fBdocker context import CONTEXT FILE|-\fP


.SH DESCRIPTION
Import a context from a tar or zip file


.SH SEE ALSO
\fBdocker-context(1)\fP
