.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-checkpoint-create - Create a checkpoint from a running container


.SH SYNOPSIS
\fBdocker checkpoint create [OPTIONS] CONTAINER CHECKPOINT\fP


.SH DESCRIPTION
Create a checkpoint from a running container


.SH OPTIONS
\fB--checkpoint-dir\fP=""
	Use a custom checkpoint storage directory

.PP
\fB--leave-running\fP[=false]
	Leave the container running after checkpoint


.SH SEE ALSO
\fBdocker-checkpoint(1)\fP
