.nh
.TH "DOCKER" "1" "Dec 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-plugin-rm - Remove one or more plugins


.SH SYNOPSIS
\fBdocker plugin rm [OPTIONS] PLUGIN [PLUGIN...]\fP


.SH DESCRIPTION
Remove one or more plugins


.SH OPTIONS
\fB-f\fP, \fB--force\fP[=false]
	Force the removal of an active plugin


.SH SEE ALSO
\fBdocker-plugin(1)\fP
