.nh
.TH "DOCKER" "1" "Aug 2023" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-push - Upload an image to a registry


.SH SYNOPSIS
.PP
\fBdocker push [OPTIONS] NAME[:TAG]\fP


.SH DESCRIPTION
.PP
Alias for \fB\fCdocker image push\fR\&.


.SH OPTIONS
.PP
\fB-a\fP, \fB--all-tags\fP[=false]
	Push all tags of an image to the repository

.PP
\fB--disable-content-trust\fP[=true]
	Skip image signing

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for push

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose output


.SH SEE ALSO
.PP
\fBdocker(1)\fP
