.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-context-import - Import a context from a tar or zip file


.SH SYNOPSIS
\fBdocker context import CONTEXT FILE|-\fP


.SH DESCRIPTION
Import a context from a tar or zip file


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for import


.SH SEE ALSO
\fBdocker-context(1)\fP
