.nh
.TH "DOCKER" "1" "Jan 2024" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-secret-inspect - Display detailed information on one or more secrets


.SH SYNOPSIS
.PP
\fBdocker secret inspect [OPTIONS] SECRET [SECRET...]\fP


.SH DESCRIPTION
.PP
Display detailed information on one or more secrets


.SH OPTIONS
.PP
\fB-f\fP, \fB--format\fP=""
	Format output using a custom template:
'json':             Print in JSON format
'TEMPLATE':         Print output using the given Go template.
Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for inspect

.PP
\fB--pretty\fP[=false]
	Print the information in a human friendly format


.SH SEE ALSO
.PP
\fBdocker-secret(1)\fP
