.nh
.TH "DOCKER" "1" "Dec 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-context - Manage contexts


.SH SYNOPSIS
\fBdocker context\fP


.SH DESCRIPTION
Manage contexts


.SH SEE ALSO
\fBdocker(1)\fP, \fBdocker-context-create(1)\fP, \fBdocker-context-export(1)\fP, \fBdocker-context-import(1)\fP, \fBdocker-context-inspect(1)\fP, \fBdocker-context-ls(1)\fP, \fBdocker-context-rm(1)\fP, \fBdocker-context-show(1)\fP, \fBdocker-context-update(1)\fP, \fBdocker-context-use(1)\fP
