.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-wait - Block until one or more containers stop, then print their exit codes


.SH SYNOPSIS
\fBdocker wait CONTAINER [CONTAINER...]\fP


.SH DESCRIPTION
Alias for \fBdocker container wait\fR\&.


.SH SEE ALSO
\fBdocker(1)\fP
