.nh
.TH "DOCKER" "1" "Jun 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-context-rm - Remove one or more contexts


.SH SYNOPSIS
\fBdocker context rm CONTEXT [CONTEXT...]\fP


.SH DESCRIPTION
Remove one or more contexts


.SH OPTIONS
\fB-f\fP, \fB--force\fP[=false]
	Force the removal of a context in use


.SH SEE ALSO
\fBdocker-context(1)\fP
