.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-commit - Create a new image from a container's changes


.SH SYNOPSIS
\fBdocker commit [OPTIONS] CONTAINER [REPOSITORY[:TAG]]\fP


.SH DESCRIPTION
Alias for \fBdocker container commit\fR\&.


.SH OPTIONS
\fB-a\fP, \fB--author\fP=""
	Author (e.g., "John Hannibal Smith hannibal@a-team.com
\[la]mailto:hannibal@a\-team.com\[ra]")

.PP
\fB-c\fP, \fB--change\fP=
	Apply Dockerfile instruction to the created image

.PP
\fB-m\fP, \fB--message\fP=""
	Commit message

.PP
\fB--no-pause\fP[=false]
	Disable pausing container during commit


.SH SEE ALSO
\fBdocker(1)\fP
