.nh
.TH "DOCKER" "1" "Jun 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-pull - Download an image from a registry


.SH SYNOPSIS
\fBdocker pull [OPTIONS] NAME[:TAG|@DIGEST]\fP


.SH DESCRIPTION
Alias for \fBdocker image pull\fR\&.


.SH OPTIONS
\fB-a\fP, \fB--all-tags\fP[=false]
	Download all tagged images in the repository

.PP
\fB--disable-content-trust\fP[=true]
	Skip image verification

.PP
\fB--platform\fP=""
	Set platform if server is multi-platform capable

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose output


.SH SEE ALSO
\fBdocker(1)\fP
