.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-node-demote - Demote one or more nodes from manager in the swarm


.SH SYNOPSIS
\fBdocker node demote NODE [NODE...]\fP


.SH DESCRIPTION
Demote one or more nodes from manager in the swarm


.SH SEE ALSO
\fBdocker-node(1)\fP
