.nh
.TH "DOCKER" "1" "Aug 2023" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-volume-update - Update a volume (cluster volumes only)


.SH SYNOPSIS
.PP
\fBdocker volume update [OPTIONS] [VOLUME]\fP


.SH DESCRIPTION
.PP
Update a volume (cluster volumes only)


.SH OPTIONS
.PP
\fB--availability\fP="active"
	Cluster Volume availability ("active", "pause", "drain")

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for update


.SH SEE ALSO
.PP
\fBdocker-volume(1)\fP
