.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-stack-ls - List stacks


.SH SYNOPSIS
\fBdocker stack ls [OPTIONS]\fP


.SH DESCRIPTION
List stacks


.SH OPTIONS
\fB--format\fP=""
	Format output using a custom template:
\&'table':            Print output in table format with column headers (default)
\&'table TEMPLATE':   Print output in table format using the given Go template
\&'json':             Print in JSON format
\&'TEMPLATE':         Print output using the given Go template.
Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates


.SH SEE ALSO
\fBdocker-stack(1)\fP
