.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-restart - Restart one or more containers


.SH SYNOPSIS
\fBdocker restart [OPTIONS] CONTAINER [CONTAINER...]\fP


.SH DESCRIPTION
Alias for \fBdocker container restart\fR\&.


.SH OPTIONS
\fB-s\fP, \fB--signal\fP=""
	Signal to send to the container

.PP
\fB-t\fP, \fB--timeout\fP=0
	Seconds to wait before killing the container


.SH SEE ALSO
\fBdocker(1)\fP
