.nh
.TH "DOCKER" "1" "Jun 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-swarm-unlock-key - Manage the unlock key


.SH SYNOPSIS
\fBdocker swarm unlock-key [OPTIONS]\fP


.SH DESCRIPTION
Manage the unlock key


.SH OPTIONS
\fB-q\fP, \fB--quiet\fP[=false]
	Only display token

.PP
\fB--rotate\fP[=false]
	Rotate unlock key


.SH SEE ALSO
\fBdocker-swarm(1)\fP
