.nh
.TH "DOCKER" "1" "Dec 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-container-top - Display the running processes of a container


.SH SYNOPSIS
\fBdocker container top CONTAINER [ps OPTIONS]\fP


.SH DESCRIPTION
Display the running process of the container. ps-OPTION can be any of the options you would pass to a Linux ps command.

.PP
All displayed information is from host's point of view.


.SH EXAMPLES
Run \fBdocker container top\fP with the ps option of -x:

.EX
$ docker container top 8601afda2b -x
PID      TTY       STAT       TIME         COMMAND
16623    ?         Ss         0:00         sleep 99999
.EE


.SH SEE ALSO
\fBdocker-container(1)\fP
