.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-push - Upload an image to a registry


.SH SYNOPSIS
\fBdocker push [OPTIONS] NAME[:TAG]\fP


.SH DESCRIPTION
Alias for \fBdocker image push\fR\&.


.SH OPTIONS
\fB-a\fP, \fB--all-tags\fP[=false]
	Push all tags of an image to the repository

.PP
\fB--platform\fP=""
	Push a platform-specific manifest as a single-platform image to the registry.
Image index won't be pushed, meaning that other manifests, including attestations won't be preserved.
\&'os[/arch[/variant]]': Explicit platform (eg. linux/amd64)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose output


.SH SEE ALSO
\fBdocker(1)\fP
