.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-search - Search Docker Hub for images


.SH SYNOPSIS
\fBdocker search [OPTIONS] TERM\fP


.SH DESCRIPTION
Search Docker Hub for images that match the specified \fBTERM\fR\&. The table
of images returned displays the name, description (truncated by default), number
of stars awarded, whether the image is official, and whether it is automated.

.SH Filter
Filter output based on these conditions:
   - stars=
   - is-automated=(true|false) (deprecated)
   - is-official=(true|false)


.SH EXAMPLES
.SH Search Docker Hub for ranked images
Search a registry for the term 'fedora' and only display those images
ranked 3 or higher:

.EX
$ docker search --filter=stars=3 fedora
NAME      DESCRIPTION                        STARS     OFFICIAL
fedora    Official Docker builds of Fedora   1150      [OK]
.EE


.SH OPTIONS
\fB-f\fP, \fB--filter\fP=
	Filter output based on conditions provided

.PP
\fB--format\fP=""
	Pretty-print search using a Go template

.PP
\fB--limit\fP=0
	Max number of search results

.PP
\fB--no-trunc\fP[=false]
	Don't truncate output


.SH SEE ALSO
\fBdocker(1)\fP
