.nh
.TH "DOCKER" "1" "Jun 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-image-save - Save one or more images to a tar archive (streamed to STDOUT by default)


.SH SYNOPSIS
\fBdocker image save [OPTIONS] IMAGE [IMAGE...]\fP


.SH DESCRIPTION
Produces a tarred repository to the standard output stream. Contains all
parent layers, and all tags + versions, or specified repo:tag.

.PP
Stream to a file instead of STDOUT by using \fB-o\fP\&.


.SH EXAMPLES
Save all fedora repository images to a fedora-all.tar and save the latest
fedora image to a fedora-latest.tar:

.EX
$ docker image save fedora > fedora-all.tar
$ docker image save --output=fedora-latest.tar fedora:latest
$ ls -sh fedora-all.tar
721M fedora-all.tar
$ ls -sh fedora-latest.tar
367M fedora-latest.tar
.EE


.SH See also
\fBdocker-image-load(1)\fP to load an image from a tar archive on STDIN.


.SH OPTIONS
\fB-o\fP, \fB--output\fP=""
	Write to a file, instead of STDOUT

.PP
\fB--platform\fP=""
	Save only the given platform variant. Formatted as "os[/arch[/variant]]" (e.g., "linux/amd64")


.SH SEE ALSO
\fBdocker-image(1)\fP
