.nh
.TH "DOCKER" "1" "Jun 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-stack - Manage Swarm stacks


.SH SYNOPSIS
\fBdocker stack [OPTIONS]\fP


.SH DESCRIPTION
Manage Swarm stacks


.SH SEE ALSO
\fBdocker(1)\fP, \fBdocker-stack-config(1)\fP, \fBdocker-stack-deploy(1)\fP, \fBdocker-stack-ls(1)\fP, \fBdocker-stack-ps(1)\fP, \fBdocker-stack-rm(1)\fP, \fBdocker-stack-services(1)\fP
