.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-volume-rm - Remove one or more volumes


.SH SYNOPSIS
\fBdocker volume rm [OPTIONS] VOLUME [VOLUME...]\fP


.SH DESCRIPTION
Remove one or more volumes. You cannot remove a volume that is in use by a container.


.SH OPTIONS
\fB-f\fP, \fB--force\fP[=false]
	Force the removal of one or more volumes

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for rm


.SH EXAMPLE
.EX

$ docker volume rm hello
hello

.EE


.SH SEE ALSO
\fBdocker-volume(1)\fP
