.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-service-rollback - Revert changes to a service's configuration


.SH SYNOPSIS
\fBdocker service rollback [OPTIONS] SERVICE\fP


.SH DESCRIPTION
Revert changes to a service's configuration


.SH OPTIONS
\fB-d\fP, \fB--detach\fP[=false]
	Exit immediately instead of waiting for the service to converge

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress progress output


.SH SEE ALSO
\fBdocker-service(1)\fP
