.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-manifest-annotate - Add additional information to a local image manifest


.SH SYNOPSIS
\fBdocker manifest annotate [OPTIONS] MANIFEST_LIST MANIFEST\fP


.SH DESCRIPTION
Add additional information to a local image manifest


.SH OPTIONS
\fB--arch\fP=""
	Set architecture

.PP
\fB--os\fP=""
	Set operating system

.PP
\fB--os-features\fP=[]
	Set operating system feature

.PP
\fB--os-version\fP=""
	Set operating system version

.PP
\fB--variant\fP=""
	Set architecture variant


.SH SEE ALSO
\fBdocker-manifest(1)\fP
