.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-image-inspect - Display detailed information on one or more images


.SH SYNOPSIS
\fBdocker image inspect [OPTIONS] IMAGE [IMAGE...]\fP


.SH DESCRIPTION
Display detailed information on one or more images


.SH OPTIONS
\fB-f\fP, \fB--format\fP=""
	Format output using a custom template:
\&'json':             Print in JSON format
\&'TEMPLATE':         Print output using the given Go template.
Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates

.PP
\fB--platform\fP=""
	Inspect a specific platform of the multi-platform image.
If the image or the server is not multi-platform capable, the command will error out if the platform does not match.
\&'os[/arch[/variant]]': Explicit platform (eg. linux/amd64)


.SH SEE ALSO
\fBdocker-image(1)\fP
