.nh
.TH "DOCKER" "1" "Dec 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-import - Import the contents from a tarball to create a filesystem image


.SH SYNOPSIS
\fBdocker import [OPTIONS] file|URL|- [REPOSITORY[:TAG]]\fP


.SH DESCRIPTION
Alias for \fBdocker image import\fR\&.


.SH OPTIONS
\fB-c\fP, \fB--change\fP=
	Apply Dockerfile instruction to the created image

.PP
\fB-m\fP, \fB--message\fP=""
	Set commit message for imported image

.PP
\fB--platform\fP=""
	Set platform if server is multi-platform capable


.SH SEE ALSO
\fBdocker(1)\fP
