.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-node-demote - Demote one or more nodes from manager in the swarm


.SH SYNOPSIS
\fBdocker node demote NODE [NODE...]\fP


.SH DESCRIPTION
Demote one or more nodes from manager in the swarm


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for demote


.SH SEE ALSO
\fBdocker-node(1)\fP
