.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-info - Display system-wide information


.SH SYNOPSIS
\fBdocker info [OPTIONS]\fP


.SH DESCRIPTION
Alias for \fBdocker system info\fR\&.


.SH OPTIONS
\fB-f\fP, \fB--format\fP=""
	Format output using a custom template:
\&'json':             Print in JSON format
\&'TEMPLATE':         Print output using the given Go template.
Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates


.SH SEE ALSO
\fBdocker(1)\fP
