.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-load - Load an image from a tar archive or STDIN


.SH SYNOPSIS
\fBdocker load [OPTIONS]\fP


.SH DESCRIPTION
Alias for \fBdocker image load\fR\&.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for load

.PP
\fB-i\fP, \fB--input\fP=""
	Read from tar archive file, instead of STDIN

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress the load output


.SH SEE ALSO
\fBdocker(1)\fP
