.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-plugin-create - Create a plugin from a rootfs and configuration. Plugin data directory must contain config.json and rootfs directory.


.SH SYNOPSIS
\fBdocker plugin create [OPTIONS] PLUGIN PLUGIN-DATA-DIR\fP


.SH DESCRIPTION
Create a plugin from a rootfs and configuration. Plugin data directory must contain config.json and rootfs directory.


.SH OPTIONS
\fB--compress\fP[=false]
	Compress the context using gzip


.SH SEE ALSO
\fBdocker-plugin(1)\fP
