.nh
.TH "DOCKER" "1" "Dec 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-node-update - Update a node


.SH SYNOPSIS
\fBdocker node update [OPTIONS] NODE\fP


.SH DESCRIPTION
Update a node


.SH OPTIONS
\fB--availability\fP=""
	Availability of the node ("active", "pause", "drain")

.PP
\fB--label-add\fP=
	Add or update a node label ("key=value")

.PP
\fB--label-rm\fP=
	Remove a node label if exists

.PP
\fB--role\fP=""
	Role of the node ("worker", "manager")


.SH SEE ALSO
\fBdocker-node(1)\fP
