.nh
.TH "DOCKER" "1" "Jun 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-trust-signer - Manage entities who can sign Docker images


.SH SYNOPSIS
\fBdocker trust signer\fP


.SH DESCRIPTION
Manage entities who can sign Docker images


.SH SEE ALSO
\fBdocker-trust(1)\fP, \fBdocker-trust-signer-add(1)\fP, \fBdocker-trust-signer-remove(1)\fP
