.nh
.TH "DOCKER" "1" "Jun 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-context-export - Export a context to a tar archive FILE or a tar stream on STDOUT.


.SH SYNOPSIS
\fBdocker context export [OPTIONS] CONTEXT [FILE|-]\fP


.SH DESCRIPTION
Export a context to a tar archive FILE or a tar stream on STDOUT.


.SH SEE ALSO
\fBdocker-context(1)\fP
