.nh
.TH "DOCKER" "1" "Feb 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-network-disconnect - Disconnect a container from a network


.SH SYNOPSIS
\fBdocker network disconnect [OPTIONS] NETWORK CONTAINER\fP


.SH DESCRIPTION
Disconnects a container from a network.

.EX
$ docker network disconnect multi-host-network container1
.EE


.SH OPTIONS
\fB-f\fP, \fB--force\fP[=false]
	Force the container to disconnect from a network

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for disconnect


.SH SEE ALSO
\fBdocker-network(1)\fP
