.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-swarm-join-token - Manage join tokens


.SH SYNOPSIS
\fBdocker swarm join-token OPTIONS
\[la]worker|manager\[ra]\fP


.SH DESCRIPTION
Manage join tokens


.SH OPTIONS
\fB-q\fP, \fB--quiet\fP[=false]
	Only display token

.PP
\fB--rotate\fP[=false]
	Rotate join token


.SH SEE ALSO
\fBdocker-swarm(1)\fP
