.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-logs - Fetch the logs of a container


.SH SYNOPSIS
\fBdocker logs [OPTIONS] CONTAINER\fP


.SH DESCRIPTION
Alias for \fBdocker container logs\fR\&.


.SH OPTIONS
\fB--details\fP[=false]
	Show extra details provided to logs

.PP
\fB-f\fP, \fB--follow\fP[=false]
	Follow log output

.PP
\fB--since\fP=""
	Show logs since timestamp (e.g. "2013-01-02T13:23:37Z") or relative (e.g. "42m" for 42 minutes)

.PP
\fB-n\fP, \fB--tail\fP="all"
	Number of lines to show from the end of the logs

.PP
\fB-t\fP, \fB--timestamps\fP[=false]
	Show timestamps

.PP
\fB--until\fP=""
	Show logs before a timestamp (e.g. "2013-01-02T13:23:37Z") or relative (e.g. "42m" for 42 minutes)


.SH SEE ALSO
\fBdocker(1)\fP
