.nh
.TH "DOCKER" "1" "Jun 2024" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-tag - Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE


.SH SYNOPSIS
.PP
\fBdocker tag SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]\fP


.SH DESCRIPTION
.PP
Alias for \fBdocker image tag\fR\&.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for tag


.SH SEE ALSO
.PP
\fBdocker(1)\fP
