.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-cp - Copy files/folders between a container and the local filesystem


.SH SYNOPSIS
\fBdocker cp [OPTIONS] CONTAINER:SRC_PATH DEST_PATH|-
	docker cp [OPTIONS] SRC_PATH|- CONTAINER:DEST_PATH\fP


.SH DESCRIPTION
Alias for \fBdocker container cp\fR\&.


.SH OPTIONS
\fB-a\fP, \fB--archive\fP[=false]
	Archive mode (copy all uid/gid information)

.PP
\fB-L\fP, \fB--follow-link\fP[=false]
	Always follow symbol link in SRC_PATH

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress progress output during copy. Progress output is automatically suppressed if no terminal is attached


.SH SEE ALSO
\fBdocker(1)\fP
