.nh
.TH "DOCKER" "1" "Jun 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-tag - Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE


.SH SYNOPSIS
\fBdocker tag SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]\fP


.SH DESCRIPTION
Alias for \fBdocker image tag\fR\&.


.SH SEE ALSO
\fBdocker(1)\fP
