.nh
.TH "DOCKER" "1" "Jan 2026" "Docker Community" "Docker User Manuals"

.SH NAME
docker-rmi - Remove one or more images


.SH SYNOPSIS
\fBdocker rmi [OPTIONS] IMAGE [IMAGE...]\fP


.SH DESCRIPTION
Alias for \fBdocker image rm\fR\&.


.SH OPTIONS
\fB-f\fP, \fB--force\fP[=false]
	Force removal of the image

.PP
\fB--no-prune\fP[=false]
	Do not delete untagged parents

.PP
\fB--platform\fP=[]
	Remove only the given platform variant. Formatted as "os[/arch[/variant]]" (e.g., "linux/amd64")


.SH SEE ALSO
\fBdocker(1)\fP
