.nh
.TH "DOCKER" "1" "Jun 2024" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-config - Manage Swarm configs


.SH SYNOPSIS
.PP
\fBdocker config\fP


.SH DESCRIPTION
.PP
Manage Swarm configs


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for config


.SH SEE ALSO
.PP
\fBdocker(1)\fP, \fBdocker-config-create(1)\fP, \fBdocker-config-inspect(1)\fP, \fBdocker-config-ls(1)\fP, \fBdocker-config-rm(1)\fP
