.nh
.TH "DOCKER" "1" "Jun 2025" "Docker Community" "Docker User Manuals"

.SH NAME
docker-image - Manage images


.SH SYNOPSIS
\fBdocker image\fP


.SH DESCRIPTION
Manage images


.SH SEE ALSO
\fBdocker(1)\fP, \fBdocker-image-build(1)\fP, \fBdocker-image-history(1)\fP, \fBdocker-image-import(1)\fP, \fBdocker-image-inspect(1)\fP, \fBdocker-image-load(1)\fP, \fBdocker-image-ls(1)\fP, \fBdocker-image-prune(1)\fP, \fBdocker-image-pull(1)\fP, \fBdocker-image-push(1)\fP, \fBdocker-image-rm(1)\fP, \fBdocker-image-save(1)\fP, \fBdocker-image-tag(1)\fP
