version: 2

defaults: &defaults
  working_directory: ~/go/src/github.com/docker/libnetwork
  docker:
    # the following image is irrelevant for the build, everything is built inside a container, check the Makefile
    - image: 'cimg/go:1.18.9'
      environment:
          dockerbuildargs: .
          dockerargs:  --privileged -e CIRCLECI

jobs:
  builder:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          reusable: true
          exclusive: false
      - run: make builder

  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          reusable: true
          exclusive: false
      - run: make build

  check:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          reusable: true
          exclusive: false
      - run: make check

  cross:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          reusable: true
          exclusive: false
      - run: make cross

  unit-tests:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          reusable: true
          exclusive: false
      - run: make unit-tests

workflows:
  version: 2
  ci:
    jobs:
      - builder
      - build:
          requires:
            - builder
      - check:
          requires:
            - builder
      - cross:
          requires:
            - builder
      - unit-tests:
          requires:
            - builder
